# Form implementation generated from reading ui file 'add_member_v5.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import pymongo
from datetime import datetime

class Ui_add_member(object):
    def setupUi(self, add_member):
        add_member.setObjectName("add_member")
        add_member.resize(439, 561)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(add_member.sizePolicy().hasHeightForWidth())
        add_member.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        add_member.setFont(font)
        add_member.setStyleSheet("#add_member{\n"
        "background-color: #f1f1f2\n"
        "}\n"
        "\n"
        "#QF_info{\n"
        "text-align:right\n"
        "}\n"
        "\n"
        "QLineEdit{\n"
        "border:none\n"
        "}\n"
        "\n"
        "QTextEdit{\n"
        "border:none\n"
        "}\n"
        "\n"
        "QDateEdit{\n"
        "border:none\n"
        "}\n"
        "\n"
        "")
        add_member.setLocale(QtCore.QLocale(QtCore.QLocale.Language.English, QtCore.QLocale.Country.UnitedStates))
        self.buttonBox = QtWidgets.QDialogButtonBox(add_member)
        self.buttonBox.setGeometry(QtCore.QRect(130, 520, 200, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.lineEdit_name = QtWidgets.QLineEdit(add_member)
        self.lineEdit_name.setGeometry(QtCore.QRect(100, 60, 321, 25))
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.lineEdit_sname = QtWidgets.QLineEdit(add_member)
        self.lineEdit_sname.setGeometry(QtCore.QRect(100, 120, 321, 25))
        self.lineEdit_sname.setObjectName("lineEdit_sname")
        self.lineEdit_mobile = QtWidgets.QLineEdit(add_member)
        self.lineEdit_mobile.setGeometry(QtCore.QRect(100, 318, 321, 24))
        self.lineEdit_mobile.setObjectName("lineEdit_mobile")
        self.dateEdit = QtWidgets.QDateEdit(add_member)
        self.dateEdit.setGeometry(QtCore.QRect(100, 250, 171, 25))
        self.dateEdit.setObjectName("dateEdit")
        self.radioButton_M = QtWidgets.QRadioButton(add_member)
        self.radioButton_M.setGeometry(QtCore.QRect(100, 190, 89, 20))
        self.radioButton_M.setObjectName("radioButton_M")
        self.radioButton_F = QtWidgets.QRadioButton(add_member)
        self.radioButton_F.setGeometry(QtCore.QRect(190, 190, 89, 20))
        self.radioButton_F.setObjectName("radioButton_F")
        self.textEdit_address = QtWidgets.QTextEdit(add_member)
        self.textEdit_address.setGeometry(QtCore.QRect(100, 390, 321, 111))
        self.textEdit_address.setObjectName("textEdit_address")
        self.mleft_addmem = QtWidgets.QWidget(add_member)
        self.mleft_addmem.setGeometry(QtCore.QRect(-10, 0, 101, 601))
        self.mleft_addmem.setStyleSheet("#mleft_addmem{\n"
        "background-color:#92a9b8\n"
        "}\n"
        "\n"
        "#QF_info{\n"
        "border:none\n"
        "\n"
        "}\n"
        "\n"
        "")
        self.mleft_addmem.setObjectName("mleft_addmem")
        self.QF_info = QtWidgets.QFrame(self.mleft_addmem)
        self.QF_info.setGeometry(QtCore.QRect(20, 30, 78, 401))
        self.QF_info.setStyleSheet("#QF_info{\n"
        "text-align:right\n"
        "}")
        self.QF_info.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.QF_info.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.QF_info.setObjectName("QF_info")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.QF_info)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_name = QtWidgets.QLabel(self.QF_info)
        self.label_name.setObjectName("label_name")
        self.verticalLayout.addWidget(self.label_name)
        self.label_sname = QtWidgets.QLabel(self.QF_info)
        self.label_sname.setObjectName("label_sname")
        self.verticalLayout.addWidget(self.label_sname)
        self.label_sex = QtWidgets.QLabel(self.QF_info)
        self.label_sex.setObjectName("label_sex")
        self.verticalLayout.addWidget(self.label_sex)
        self.label_birthdate = QtWidgets.QLabel(self.QF_info)
        self.label_birthdate.setObjectName("label_birthdate")
        self.verticalLayout.addWidget(self.label_birthdate)
        self.label_mobile = QtWidgets.QLabel(self.QF_info)
        self.label_mobile.setObjectName("label_mobile")
        self.verticalLayout.addWidget(self.label_mobile)
        self.label_address = QtWidgets.QLabel(self.QF_info)
        self.label_address.setObjectName("label_address")
        self.verticalLayout.addWidget(self.label_address)
        self.edit_member_label = QtWidgets.QLabel(add_member)
        self.edit_member_label.setGeometry(QtCore.QRect(180, 20, 171, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.edit_member_label.setFont(font)
        self.edit_member_label.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.edit_member_label.setObjectName("edit_member_label")

        self.retranslateUi(add_member)
        self.buttonBox.accepted.connect(self.insert_member) 
        self.buttonBox.accepted.connect(add_member.accept) 
        self.buttonBox.rejected.connect(add_member.reject) 
        QtCore.QMetaObject.connectSlotsByName(add_member)

    def buttonQuit(self):
        self.close()

    def insert_member(self):
        try:
                client = pymongo.MongoClient("mongodb://localhost:27017/")
                database = client["db_Quiz1"]
                collection = database["members"]
                doc_count = collection.find().count()
        
                b_date = self.dateEdit.dateTime()
                birthdate = b_date.toPyDateTime()
                today = datetime.today()
                age = today.year - birthdate.year - ((today.month, today.day) < (birthdate.month, birthdate.day))
                mem_name = self.lineEdit_name.text()
                mem_sname = self.lineEdit_sname.text()
                mem_mobile = self.lineEdit_mobile.text()
                mem_address = self.textEdit_address.toPlainText()

                if self.radioButton_M.isChecked():
                        member_sex = self.radioButton_M.text()
                elif self.radioButton_F.isChecked():
                        member_sex = self.radioButton_F.text()
                else:
                        member_sex = ""

                new_member_data = {
                'Cus_ID': doc_count,
                'Name': mem_name,
                'Surname': mem_sname,
                'Sex': member_sex,
                'Birthdate': birthdate,
                'Age': age,
                'Mobile': mem_mobile,
                'Address': mem_address,
                'RegisterDate': datetime.today()
                }
                response = collection.insert_one(new_member_data)
                print("Successfully Added New Member Data")
                

        except:
                print("Error in adding New Member Data")

    def retranslateUi(self, add_member):
        _translate = QtCore.QCoreApplication.translate
        add_member.setWindowTitle(_translate("add_member", "Dialog"))
        self.radioButton_M.setText(_translate("add_member", "Male"))
        self.radioButton_F.setText(_translate("add_member", "Female"))
        self.label_name.setText(_translate("add_member", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:700; color:#020202;\">Name:</span></p></body></html>"))
        self.label_sname.setText(_translate("add_member", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:700; color:#020202;\">Surname</span></p></body></html>"))
        self.label_sex.setText(_translate("add_member", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:700;\">Sex</span></p></body></html>"))
        self.label_birthdate.setText(_translate("add_member", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:700;\">Birthdate</span></p></body></html>"))
        self.label_mobile.setText(_translate("add_member", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:700;\">Mobile</span></p></body></html>"))
        self.label_address.setText(_translate("add_member", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:700;\">Address</span></p></body></html>"))
        self.edit_member_label.setText(_translate("add_member", "ADD MEMBER DATA"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    add_member = QtWidgets.QDialog()
    ui = Ui_add_member()
    ui.setupUi(add_member)
    add_member.show()
    sys.exit(app.exec())
