# Form implementation generated from reading ui file 'edit_member_v5.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import pymongo
from datetime import datetime


class Ui_edit_member(object):
    def setupUi(self, edit_member):
        edit_member.setObjectName("edit_member")
        edit_member.resize(439, 601)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(edit_member.sizePolicy().hasHeightForWidth())
        edit_member.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        edit_member.setFont(font)
        edit_member.setStyleSheet("#edit_member{background-color: #f1f1f2}\n"
"#QF_info{text-align:right}\n"
"QLineEdit{border:none}\n"
"QTextEdit{border:none}\n"
"QDateEdit{border:none\n"
"}\n"
"\n"
"")
        edit_member.setLocale(QtCore.QLocale(QtCore.QLocale.Language.English, QtCore.QLocale.Country.UnitedStates))
        self.buttonBox = QtWidgets.QDialogButtonBox(edit_member)
        self.buttonBox.setGeometry(QtCore.QRect(130, 550, 200, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.lineEdit_name = QtWidgets.QLineEdit(edit_member)
        self.lineEdit_name.setGeometry(QtCore.QRect(100, 98, 321, 25))
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.lineEdit_sname = QtWidgets.QLineEdit(edit_member)
        self.lineEdit_sname.setGeometry(QtCore.QRect(100, 162, 321, 25))
        self.lineEdit_sname.setObjectName("lineEdit_sname")
        self.lineEdit_mobile = QtWidgets.QLineEdit(edit_member)
        self.lineEdit_mobile.setGeometry(QtCore.QRect(100, 356, 321, 25))
        self.lineEdit_mobile.setObjectName("lineEdit_mobile")
        self.dateEdit = QtWidgets.QDateEdit(edit_member)
        self.dateEdit.setGeometry(QtCore.QRect(300, 290, 121, 25))
        self.dateEdit.setObjectName("dateEdit")
        self.radioButton_M = QtWidgets.QRadioButton(edit_member)
        self.radioButton_M.setGeometry(QtCore.QRect(300, 230, 61, 20))
        self.radioButton_M.setObjectName("radioButton_M")
        self.radioButton_F = QtWidgets.QRadioButton(edit_member)
        self.radioButton_F.setGeometry(QtCore.QRect(360, 230, 71, 20))
        self.radioButton_F.setObjectName("radioButton_F")
        self.textEdit_address = QtWidgets.QTextEdit(edit_member)
        self.textEdit_address.setGeometry(QtCore.QRect(100, 426, 321, 111))
        self.textEdit_address.setObjectName("textEdit_address")
        self.mleft_addmem = QtWidgets.QWidget(edit_member)
        self.mleft_addmem.setGeometry(QtCore.QRect(-10, 0, 101, 601))
        self.mleft_addmem.setStyleSheet("#mleft_addmem{background-color:#f2b8c6}\n"
"#QF_info{border:none}\n"
"\n"
"")
        self.mleft_addmem.setObjectName("mleft_addmem")
        self.QF_info = QtWidgets.QFrame(self.mleft_addmem)
        self.QF_info.setGeometry(QtCore.QRect(20, 70, 78, 401))
        self.QF_info.setStyleSheet("#QF_info{\n"
"text-align:right\n"
"}")
        self.QF_info.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.QF_info.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.QF_info.setObjectName("QF_info")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.QF_info)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_name = QtWidgets.QLabel(self.QF_info)
        self.label_name.setObjectName("label_name")
        self.verticalLayout.addWidget(self.label_name)
        self.label_sname = QtWidgets.QLabel(self.QF_info)
        self.label_sname.setObjectName("label_sname")
        self.verticalLayout.addWidget(self.label_sname)
        self.label_sex = QtWidgets.QLabel(self.QF_info)
        self.label_sex.setObjectName("label_sex")
        self.verticalLayout.addWidget(self.label_sex)
        self.label_birthdate = QtWidgets.QLabel(self.QF_info)
        self.label_birthdate.setObjectName("label_birthdate")
        self.verticalLayout.addWidget(self.label_birthdate)
        self.label_mobile = QtWidgets.QLabel(self.QF_info)
        self.label_mobile.setObjectName("label_mobile")
        self.verticalLayout.addWidget(self.label_mobile)
        self.label_address = QtWidgets.QLabel(self.QF_info)
        self.label_address.setObjectName("label_address")
        self.verticalLayout.addWidget(self.label_address)
        self.edit_member_label = QtWidgets.QLabel(edit_member)
        self.edit_member_label.setGeometry(QtCore.QRect(170, 10, 171, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.edit_member_label.setFont(font)
        self.edit_member_label.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.edit_member_label.setObjectName("edit_member_label")
        self.lineEdit_search = QtWidgets.QLineEdit(edit_member)
        self.lineEdit_search.setGeometry(QtCore.QRect(200, 50, 121, 25))
        self.lineEdit_search.setObjectName("lineEdit_search")
        self.searchID_label = QtWidgets.QLabel(edit_member)
        self.searchID_label.setGeometry(QtCore.QRect(120, 53, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        self.searchID_label.setFont(font)
        self.searchID_label.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.searchID_label.setObjectName("searchID_label")
        self.pushButton_search = QtWidgets.QPushButton(edit_member)
        self.pushButton_search.setGeometry(QtCore.QRect(340, 50, 75, 24))
        self.pushButton_search.setObjectName("pushButton_search")
        self.display_birthdate = QtWidgets.QLabel(edit_member)
        self.display_birthdate.setGeometry(QtCore.QRect(150, 290, 81, 25))
        self.display_birthdate.setStyleSheet("#display_birthdate{background-color:white}")
        self.display_birthdate.setText("")
        self.display_birthdate.setObjectName("display_birthdate")
        self.label_currentDate = QtWidgets.QLabel(edit_member)
        self.label_currentDate.setGeometry(QtCore.QRect(100, 293, 49, 16))
        font = QtGui.QFont()
        font.setBold(False)
        self.label_currentDate.setFont(font)
        self.label_currentDate.setObjectName("label_currentDate")
        self.label_edittodate = QtWidgets.QLabel(edit_member)
        self.label_edittodate.setGeometry(QtCore.QRect(250, 294, 49, 16))
        font = QtGui.QFont()
        font.setBold(False)
        self.label_edittodate.setFont(font)
        self.label_edittodate.setObjectName("label_edittodate")
        self.label_currentSex = QtWidgets.QLabel(edit_member)
        self.label_currentSex.setGeometry(QtCore.QRect(100, 230, 49, 16))
        font = QtGui.QFont()
        font.setBold(False)
        self.label_currentSex.setFont(font)
        self.label_currentSex.setObjectName("label_currentSex")
        self.display_sex = QtWidgets.QLabel(edit_member)
        self.display_sex.setGeometry(QtCore.QRect(150, 230, 81, 25))
        self.display_sex.setStyleSheet("#display_sex{background-color:white}")
        self.display_sex.setText("")
        self.display_sex.setObjectName("display_sex")
        self.label_edittodate_2 = QtWidgets.QLabel(edit_member)
        self.label_edittodate_2.setGeometry(QtCore.QRect(250, 230, 49, 16))
        font = QtGui.QFont()
        font.setBold(False)
        self.label_edittodate_2.setFont(font)
        self.label_edittodate_2.setObjectName("label_edittodate_2")

        self.retranslateUi(edit_member)
        self.buttonBox.accepted.connect(self.adjust_member) 
        self.buttonBox.accepted.connect(edit_member.accept) # type: ignore
        self.buttonBox.rejected.connect(edit_member.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(edit_member)

        #Add code-------------
        self.pushButton_search.clicked.connect(self.search_mem_data)

    def search_mem_data(self):
        try:
                client = pymongo.MongoClient("mongodb://localhost:27017/")
                database = client["db_Quiz1"]
                collection = database["members"]
                doc_count = collection.find().count()

                search = self.lineEdit_search.text()
                search_id = int(search)
             
                #display search
                find_search = collection.find_one({'Cus_ID':search_id})
                self.lineEdit_name.setText(find_search['Name'])
                self.lineEdit_sname.setText(find_search['Surname'])
                self.lineEdit_mobile.setText(find_search['Mobile'])
                self.textEdit_address.setText(find_search['Address'])
                self.display_sex.setText(find_search['Sex'])
                self.display_birthdate.setText(str(find_search['Birthdate'].date()))

                if (find_search['Sex'] == 'Male'):
                    self.radioButton_M.setChecked
                else:
                    self.radioButton_F.setChecked

        except:
                print("Error")

    def adjust_member(self):
        try:

                client = pymongo.MongoClient("mongodb://localhost:27017/")
                database = client["db_Quiz1"]
                collection = database["members"]
                doc_count = collection.find().count()

                search = self.lineEdit_search.text()
                search_id = int(search)
                find_search = collection.find_one({'Cus_ID':search_id})
                mem_name = self.lineEdit_name.text()
                mem_sname = self.lineEdit_sname.text()
                mem_mobile = self.lineEdit_mobile.text()
                mem_address = self.textEdit_address.toPlainText()

                b_date = self.dateEdit.dateTime()
                birthdate = b_date.toPyDateTime()
        
                if self.radioButton_M.isChecked():
                        member_sex = self.radioButton_M.text()
                elif self.radioButton_F.isChecked():
                        member_sex = self.radioButton_F.text()
                else:
                        member_sex = ""

                new_member_data = {
                'Cus_ID': search_id,
                'Name': mem_name,
                'Surname': mem_sname,
                'Sex': member_sex,
                'Birthdate': birthdate,
                'Age': find_search['Age'],
                'Mobile': mem_mobile,
                'Address': mem_address,
                'RegisterDate': find_search['RegisterDate']
                }
                collection.remove({'Cus_ID':int(self.lineEdit_search.text())})
                collection.insert_one(new_member_data)
            
        except:
                print("Error")

    def retranslateUi(self, edit_member):
        _translate = QtCore.QCoreApplication.translate
        edit_member.setWindowTitle(_translate("edit_member", "Dialog"))
        self.radioButton_M.setText(_translate("edit_member", "Male"))
        self.radioButton_F.setText(_translate("edit_member", "Female"))
        self.label_name.setText(_translate("edit_member", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:700; color:#020202;\">Name:</span></p></body></html>"))
        self.label_sname.setText(_translate("edit_member", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:700; color:#010101;\">Surname</span></p></body></html>"))
        self.label_sex.setText(_translate("edit_member", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:700; color:#010101;\">Sex</span></p></body></html>"))
        self.label_birthdate.setText(_translate("edit_member", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:700; color:#010101;\">Birthdate</span></p></body></html>"))
        self.label_mobile.setText(_translate("edit_member", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:700; color:#010101;\">Mobile</span></p></body></html>"))
        self.label_address.setText(_translate("edit_member", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:700; color:#010101;\">Address</span></p></body></html>"))
        self.edit_member_label.setText(_translate("edit_member", "EDIT MEMBER DATA"))
        self.searchID_label.setText(_translate("edit_member", "Search ID"))
        self.pushButton_search.setText(_translate("edit_member", "Search"))
        self.label_currentDate.setText(_translate("edit_member", "Current"))
        self.label_edittodate.setText(_translate("edit_member", "<html><head/><body><p><span style=\" color:#eb1809;\">Edit to</span></p></body></html>"))
        self.label_currentSex.setText(_translate("edit_member", "Current"))
        self.label_edittodate_2.setText(_translate("edit_member", "<html><head/><body><p><span style=\" color:#eb1809;\">Edit to</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    edit_member = QtWidgets.QDialog()
    ui = Ui_edit_member()
    ui.setupUi(edit_member)
    edit_member.show()
    sys.exit(app.exec())
