# Form implementation generated from reading ui file 'remove_member.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import pymongo


class Ui_remove_member(object):
    def setupUi(self, remove_member):
        remove_member.setObjectName("remove_member")
        remove_member.resize(439, 602)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(remove_member.sizePolicy().hasHeightForWidth())
        remove_member.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        remove_member.setFont(font)
        remove_member.setStyleSheet("#edit_member{background-color: #f1f1f2}\n"
"#QF_info{text-align:right}\n"
"QLineEdit{border:none}\n"
"QTextEdit{border:none}\n"
"QDateEdit{border:none\n"
"}\n"
"\n"
"")
        remove_member.setLocale(QtCore.QLocale(QtCore.QLocale.Language.English, QtCore.QLocale.Country.UnitedStates))
        self.buttonBox = QtWidgets.QDialogButtonBox(remove_member)
        self.buttonBox.setGeometry(QtCore.QRect(130, 550, 200, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.mleft_addmem = QtWidgets.QWidget(remove_member)
        self.mleft_addmem.setGeometry(QtCore.QRect(-10, 0, 101, 601))
        self.mleft_addmem.setStyleSheet("#mleft_addmem{background-color:black}\n"
"#QF_info{border:none}\n"
"\n"
"")
        self.mleft_addmem.setObjectName("mleft_addmem")
        self.QF_info = QtWidgets.QFrame(self.mleft_addmem)
        self.QF_info.setGeometry(QtCore.QRect(20, 70, 78, 401))
        self.QF_info.setStyleSheet("#QF_info{\n"
"text-align:right\n"
"}")
        self.QF_info.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.QF_info.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.QF_info.setObjectName("QF_info")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.QF_info)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_name = QtWidgets.QLabel(self.QF_info)
        self.label_name.setObjectName("label_name")
        self.verticalLayout.addWidget(self.label_name)
        self.label_sname = QtWidgets.QLabel(self.QF_info)
        self.label_sname.setObjectName("label_sname")
        self.verticalLayout.addWidget(self.label_sname)
        self.label_sex = QtWidgets.QLabel(self.QF_info)
        self.label_sex.setObjectName("label_sex")
        self.verticalLayout.addWidget(self.label_sex)
        self.label_birthdate = QtWidgets.QLabel(self.QF_info)
        self.label_birthdate.setObjectName("label_birthdate")
        self.verticalLayout.addWidget(self.label_birthdate)
        self.label_mobile = QtWidgets.QLabel(self.QF_info)
        self.label_mobile.setObjectName("label_mobile")
        self.verticalLayout.addWidget(self.label_mobile)
        self.label_address = QtWidgets.QLabel(self.QF_info)
        self.label_address.setObjectName("label_address")
        self.verticalLayout.addWidget(self.label_address)
        self.remove_member_label = QtWidgets.QLabel(remove_member)
        self.remove_member_label.setGeometry(QtCore.QRect(170, 10, 191, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.remove_member_label.setFont(font)
        self.remove_member_label.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.remove_member_label.setObjectName("remove_member_label")
        self.lineEdit_search = QtWidgets.QLineEdit(remove_member)
        self.lineEdit_search.setGeometry(QtCore.QRect(200, 50, 121, 25))
        self.lineEdit_search.setObjectName("lineEdit_search")
        self.search_member_label = QtWidgets.QLabel(remove_member)
        self.search_member_label.setGeometry(QtCore.QRect(130, 53, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        self.search_member_label.setFont(font)
        self.search_member_label.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.search_member_label.setObjectName("search_member_label")
        self.pushButton_search = QtWidgets.QPushButton(remove_member)
        self.pushButton_search.setGeometry(QtCore.QRect(340, 50, 75, 24))
        self.pushButton_search.setObjectName("pushButton_search")
        self.display_name = QtWidgets.QLabel(remove_member)
        self.display_name.setGeometry(QtCore.QRect(100, 96, 321, 25))
        self.display_name.setStyleSheet("#display_name{background-color:white}")
        self.display_name.setText("")
        self.display_name.setObjectName("display_name")
        self.textBrowser_address = QtWidgets.QTextBrowser(remove_member)
        self.textBrowser_address.setGeometry(QtCore.QRect(100, 426, 321, 111))
        self.textBrowser_address.setObjectName("textBrowser_address")
        self.display_sname = QtWidgets.QLabel(remove_member)
        self.display_sname.setGeometry(QtCore.QRect(100, 160, 321, 25))
        self.display_sname.setStyleSheet("#display_sname{background-color:white}")
        self.display_sname.setText("")
        self.display_sname.setObjectName("display_sname")
        self.display_sex = QtWidgets.QLabel(remove_member)
        self.display_sex.setGeometry(QtCore.QRect(100, 230, 321, 25))
        self.display_sex.setStyleSheet("#display_sex{background-color:white}")
        self.display_sex.setText("")
        self.display_sex.setObjectName("display_sex")
        self.display_birthdate = QtWidgets.QLabel(remove_member)
        self.display_birthdate.setGeometry(QtCore.QRect(100, 290, 321, 25))
        self.display_birthdate.setStyleSheet("#display_birthdate{background-color:white}")
        self.display_birthdate.setText("")
        self.display_birthdate.setObjectName("display_birthdate")
        self.display_mobile = QtWidgets.QLabel(remove_member)
        self.display_mobile.setGeometry(QtCore.QRect(100, 360, 321, 25))
        self.display_mobile.setStyleSheet("#display_mobile{background-color:white}")
        self.display_mobile.setText("")
        self.display_mobile.setObjectName("display_mobile")

        self.retranslateUi(remove_member)
        self.buttonBox.accepted.connect(self.remove_mem_data) 
        self.buttonBox.accepted.connect(remove_member.accept) # type: ignore
        self.buttonBox.rejected.connect(remove_member.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(remove_member)

        #Add code-------------
        self.pushButton_search.clicked.connect(self.search_mem_data)


    def search_mem_data(self):
        client = pymongo.MongoClient("mongodb://localhost:27017/")
        database = client["db_Quiz1"]
        collection = database["members"]
        search = self.lineEdit_search.text()
        search_id = int(search)
             
        #display search
        find_search = collection.find_one({'Cus_ID':search_id})
        self.display_name.setText(find_search['Name'])
        self.display_sname.setText(find_search['Surname'])
        self.display_sex.setText(find_search['Sex'])
        self.display_birthdate.setText(str(find_search['Birthdate'].date()))
        self.display_mobile.setText(find_search['Mobile'])
        self.textBrowser_address.setText(find_search['Address'])
     
    def remove_mem_data(self):
        client = pymongo.MongoClient("mongodb://localhost:27017/")
        database = client["db_Quiz1"]
        collection = database["members"]
       
        mem_name = self.display_name.text()
        mem_sname = self.display_sname.text()
        mem_sex = self.display_sex.text()
        mem_mobile = self.display_mobile.text()
        mem_address = self.textBrowser_address.toPlainText()

     

        collection.remove({'Cus_ID':int(self.lineEdit_search.text())})


    def retranslateUi(self, remove_member):
        _translate = QtCore.QCoreApplication.translate
        remove_member.setWindowTitle(_translate("remove_member", "Dialog"))
        self.label_name.setText(_translate("remove_member", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:700; color:#ffffff;\">Name:</span></p></body></html>"))
        self.label_sname.setText(_translate("remove_member", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:700; color:#ffffff;\">Surname</span></p></body></html>"))
        self.label_sex.setText(_translate("remove_member", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:700; color:#ffffff;\">Sex</span></p></body></html>"))
        self.label_birthdate.setText(_translate("remove_member", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:700; color:#ffffff;\">Birthdate</span></p></body></html>"))
        self.label_mobile.setText(_translate("remove_member", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:700; color:#ffffff;\">Mobile</span></p></body></html>"))
        self.label_address.setText(_translate("remove_member", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:700; color:#ffffff;\">Address</span></p></body></html>"))
        self.remove_member_label.setText(_translate("remove_member", "REMOVE MEMBER DATA"))
        self.search_member_label.setText(_translate("remove_member", "Search ID"))
        self.pushButton_search.setText(_translate("remove_member", "Search"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    remove_member = QtWidgets.QDialog()
    ui = Ui_remove_member()
    ui.setupUi(remove_member)
    remove_member.show()
    sys.exit(app.exec())
